import type { Database } from './database.types'

/**
 * Corrected row types.
 *
 * database.types.ts is generated by `npm run db:types` and is overwritten on
 * every regeneration, so nothing hand-written may live there. It is also wrong
 * about nullability for set-returning functions: Postgres reports every column
 * of a RETURNS TABLE as non-null, so the generator types `description` as
 * `string` when it is really `string | null`.
 *
 * These types restate the nullable columns accurately. Use them instead of the
 * generated Returns types.
 */

type RawNearbyRow =
  Database['public']['Functions']['nearby_activities']['Returns'][number]

export type NearbyActivity = Omit<
  RawNearbyRow,
  | 'description'
  | 'activity_distance_m'
  | 'pace_seconds_per_km'
  | 'level'
  | 'owner_avatar_url'
  | 'max_participants'
> & {
  description: string | null
  /** Route length in metres, not a distance from the viewer. */
  activity_distance_m: number | null
  pace_seconds_per_km: number | null
  level: Database['public']['Enums']['activity_level'] | null
  owner_avatar_url: string | null
  /** NULL means no participant limit. */
  max_participants: number | null
}

export type ActivityRow = Database['public']['Tables']['activities']['Row']
export type ProfileRow = Database['public']['Tables']['profiles']['Row']
export type CommentRow = Database['public']['Tables']['comments']['Row']
export type JoinRequestRow = Database['public']['Tables']['join_requests']['Row']
export type ActivityStatus = Database['public']['Enums']['activity_status']
export type ActivityLevel = Database['public']['Enums']['activity_level']
export type JoinRequestStatus = Database['public']['Enums']['join_request_status']
